name: CI/CD Pipeline

on:
  workflow_dispatch:
  

jobs:
  build:
    name: Run Python App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Pull Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile 
          pull: true
          tags: task-manager:latest
        
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/khushis/task-manager:latest
          
      - name: Run Python script
        run: |
          python3 test_agriculture.py
          